server:
  port: 5000

spring:
  application:
    name: service-manage-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/breakingdawn?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: pt123

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.miracle.domain
  configuration:
    map-underscore-to-camel-case: true


eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:9120/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id

info:
  app.Name: service-manage-system
